#!/bin/bash 

##############################################################################
# --- BASH SHELL SCRIPT FOR BUILDING CSI COMMS CODE ---
# 
# ---> Run 'source build.sh' from the Linux cmd line to build the code
# ---> build.sh MUST be in the parent directory of /bin, /debug, and /source
# ---> Output .hex file will be in /bin binary
# ---> /source directory will contain source code, assembler listings, and
#      object files
# ---> /debug directory will contain debug information files generated by
#      the SDCC compiler, see the SDCC user manual for more information
##############################################################################

# Where the files are
SRC_DIR="./source"

# Destination directory for outputted hex file
BIN_DEST_DIR="./bin"

# Destination directory for debug files
DEBUG_DEST_DIR="./debug"

echo " "
echo "CSI COMMS CODE BUILD PROCESS STARTED"

# Print out directory structure information
echo " "
echo "-------DIRECTORY INFORMATION-------"
echo "***   SOURCE DIR: $SRC_DIR" 
echo "***   BINARY DESTINATION DIR: $BIN_DEST_DIR" 
echo "***   DEBUG DESTINATION DIR: $DEBUG_DEST_DIR" 
echo "-----------------------------------"
echo " "

# Compile source file
echo "-------------COMPILING-------------"
sdcc -c ./source/Radio.c
echo "***   Compiling Radio.c"
echo "***   Compilation complete"
echo "-----------------------------------"
echo " "

echo "---------ORGANIZING FILES----------"
# Move and rename files to fit directory strucutre
# Check to see if Radio.asm, Radio.lst, Radio.rel, and Radio.sym exists
if [ -e "./Radio.asm" ] 
then
	echo "***   MOVING .asm FILE TO SOURCE DIRECTORY"
	mv ./Radio.asm $DEBUG_DEST_DIR
else
	echo "!!! ERROR !!! .asm FILE NOT FOUND - CHECK IF COMPILATION WAS SUCCESSFUL"
fi

if [ -e "./Radio.lst" ]
then
	echo "***   MOVING .lst FILE TO SOURCE DIRECTORY"
	mv ./Radio.lst $SRC_DIR
else
	echo "!!! ERROR !!! .lst FILE NOT FOUND - CHECK IF COMPILATION WAS SUCCESSFUL"
fi

if [ -e "./Radio.rel" ]
then
	echo "***   MOVING .rel FILE TO SOURCE DIRECTORY"
	mv ./Radio.rel $SRC_DIR
else
	echo "!!! ERROR !!! .rel FILE NOT FOUND - CHECK IF COMPILATION WAS SUCCESSFUL"
fi

if [ -e "./Radio.sym" ]
then
	echo "***   MOVING .sym FILE TO DEBUG DIRECTORY"
	mv ./Radio.sym $DEBUG_DEST_DIR
else
	echo "!!! ERROR !!! .sym FILE NOT FOUND - CHECK IF COMPILATION WAS SUCCESSFUL"
fi
echo "-----------------------------------"
echo " "


echo "--------LINKING OBJECT FILES-------"
# Link object files and generate output hex file
sdcc ./source/Radio.rel
echo "*** Linking Radio.rel"
echo "*** Linking complete"
echo "-----------------------------------"
echo " "

echo "---------ORGANIZING FILES----------"
# Check to see if Radio.ihx exists
if [ -e "./Radio.ihx" ]
then
	echo "***   MOVING .ihx FILE TO BIN DIRECTORY"
	mv ./Radio.ihx $BIN_DEST_DIR/Radio.hex
else
	echo "HEX FILE NOT FOUND - CHECK IF COMPILATION WAS SUCCESSFUL"
fi

if [ -e "./Radio.lk" ]
then
	echo "***   MOVING .sym FILE TO DEBUG DIRECTORY"
	mv ./Radio.lk $DEBUG_DEST_DIR
else
	echo "!!! ERROR !!! .lk FILE NOT FOUND - CHECK IF COMPILATION WAS SUCCESSFUL"
fi

if [ -e "./Radio.map" ]
then
	echo "***   MOVING .map FILE TO DEBUG DIRECTORY"
	mv ./Radio.map $DEBUG_DEST_DIR
else
	echo "!!! ERROR !!! .map FILE NOT FOUND - CHECK IF COMPILATION WAS SUCCESSFUL"
fi

if [ -e "./Radio.mem" ]
then
	echo "***   MOVING .mem FILE TO DEBUG DIRECTORY"
	mv ./Radio.mem $DEBUG_DEST_DIR
else
	echo "!!! ERROR !!! .mem FILE NOT FOUND - CHECK IF COMPILATION WAS SUCCESSFUL"
fi
echo "-----------------------------------"
echo " "




